eia_api:
  wti_prices:
    url: https://api.eia.gov/v2/petroleum/pri/spt/data
    payload: 
      api_key: null
      facets[product][]: EPCWTI
      start: '2015-01-01'
      sort[0][column]: period
      sort[0][direction]: asc
      frequency: daily
      data[0]: value
  oil_production:
    url: https://api.eia.gov/v2/petroleum/crd/crpdn/data
    payload:
      api_key: null
      facets[product][]: EPC0
      start: '2015-01-01'
      sort[0][column]: period
      sort[0][direction]: asc
      data[0]: value
    date_intervals:
      - ['2015-01','2020-02']
      - ['2020-02','2025-03']
      - ['2025-03',null]
  input_utilization:
    url: https://api.eia.gov/v2/petroleum/pnp/wiup/data
    payload:
      api_key: null
      facets[product][]: EPC0
      start: '2015-01-01'
      sort[0][column]: period
      sort[0][direction]: asc
      data[0]: value
  gasoline_price:
    url: https://api.eia.gov/v2/petroleum/pri/gnd/data
    payload:
      api_key: null
      facets[product][]: EPM0
      start: '2015-01-01'
      sort[0][column]: period
      sort[0][direction]: asc
      data[0]: value
    date_intervals:
    - ['2015-01-01','2017-12-31']
    - ['2017-12-31','2021-03-31']
    - ['2021-03-31','2024-06-30']
    - ['2024-06-30',null]
  imports_and_exports:
    url: https://api.eia.gov/v2/petroleum/move/wkly/data
    payload:
      api_key: null
      facets[product][]: EPC0
      start: '2015-01-01'
      sort[0][column]: period
      sort[0][direction]: asc
      data[0]: value
    date_intervals:
    - ['2015-01-01','2023-08-31']
    - ['2023-08-31',null]
  oil_supplied:
    url: https://api.eia.gov/v2/petroleum/cons/psup/data
    payload:
      api_key: null
      facets[product][]: EPC0
      start: '2015-01-01'
      sort[0][column]: period
      sort[0][direction]: asc
      data[0]: value
fred_api:
  us_dollar_index: 
    series_id: DTWEXBGS
    api_key: null
    file_type: json
    observation_start: '2015-01-01'
  volatility_index:
    series_id: VIXCLS
    api_key: null
    file_type: json
    observation_start: '2015-01-01'
  cpi_energy:
    series_id: CPIENGSL
    api_key: null
    file_type: json
    observation_start: '2015-01-01'